// mutations 变量名

export const SET_COURSE = 'SET_COURSE';
export const SET_USERGUID = 'SET_USERGUID';
export const RECORD_USERINFO = 'RECORD_USERINFO';
export const RECORD_THRIDPARTY = 'RECORD_THRIDPARTY';
export const RECORD_THRIDPARTYINFO = 'RECORD_THRIDPARTYINFO';
