// mutations 变量名

export const SET_COURSE = 'SET_COURSE';
export const SET_USERGUID = 'SET_USERGUID';
export const UPDATA_USERGUID = 'UPDATA_USERGUID';
export const SET_BEFORELOGINPAGE = 'SET_BEFORELOGINPAGE';
export const UPDATA_BEFORELOGINPAGE = 'UPDATA_BEFORELOGINPAGE';
export const RECORD_USERINFO = 'RECORD_USERINFO';
export const RECORD_THIRDPARTY = 'RECORD_THIRDPARTY';
export const RECORD_THIRDPARTYINFO = 'RECORD_THIRDPARTYINFO';
export const LOGIN_IN = 'LOGIN_IN';
export const LOGIN_OUT = 'LOGIN_OUT';
